playlistdriver:	playlist.h playlistdriver.cpp song.h song.cpp playlist.cpp
			g++ -std=c++11 playlistdriver.cpp song.cpp playlist.cpp -o playlistdriver
run: 		playlistdriver
			
clean:		
			rm -f playlistdriver